### ISSUE TITLE
Logitech K750 keyboard lighting value not updated

### ISSUE THREAD

**Issue by carscott** [pwr/Solaar#124]
The lux value is not updated from the keyboard button or from the solaar icon.

The only way to get the new value  is to restart solaar. Is this the expected behaviour

Using Linux Mint 13 with all updates on Acer Aspire Revo R3600

Python 2.7.3 (default, Apr 10 2013, 05:09:49)

**Comment by macchapman** [comment]
This problem also occurs on Fedora 24. When Solaar is first opened, the lux value for the K750 keyboard is displayed. If I then click on a different unifying receiver and then switch back to clicking on the receiver for the K750 solar keyboard, the lux value and the icon disappear. The only way to get the lux value back is to stop Solaar and restart it.

**Comment by macchapman** [comment]
Just noticed that if you press the "sun" button on the keyboard, next to the happy and sad faces, the lux reading appears on the Solaar GUI. I suppose that this is the expected behaviour, therefore this issue can be closed. except that it would be nice if a message was shown in the GUI saying "press Sun button to get lux value"

**Comment by Lekensteyn** [comment]
@macchapman can you try the git (master) version and see if the problem persists?

**Comment by macchapman** [comment]
Ok.  Will do. Thanks Peter.

Michael

----
Michael Chapman

Mentor Graphics
Tel: +44 7785 231398


On 20 Mar 2017, at 22:53, Peter Wu <notifications@github.com<mailto:notifications@github.com>> wrote:


@macchapman<https://github.com/macchapman> can you try the git (master) version and see if the problem persists?

-

**Comment by macchapman** [comment]
Hi Peter
I cloned the fit repository and the problem seems to have gone away. Thanks for the fix!

Michael

----
Michael Chapman

Mentor Graphics
Tel: +44 7785 231398


On 20 Mar 2017, at 22:53, Peter Wu <notifications@github.com<mailto:notifications@github.com>> wrote:


@macchapman<https://github.com/macchapman> can you try the git (master) version and see if the problem persists?

-

**Comment by Lekensteyn** [comment]
Thanks for your feedback!
