### ISSUE TITLE
Support Dell Universal Receiver

### ISSUE THREAD

**Issue by shred** [pwr/Solaar#280]
The Dell KM714 wireless mouse and keyboard combo originally came with a Logitech Unifying Receiver, but now Dell delivers their own "Universal Receiver" with the same combo. It all still looks very much like a rebranded Unifying Receiver with its own USB ID.

Is it possible to add Dell Universal support to Solaar? I would be happy if I could enable keyboard encryption...

```
Bus 002 Device 018: ID 413c:301c Dell Computer Corp. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        32
  idVendor           0x413c Dell Computer Corp.
  idProduct          0x301c 
  bcdDevice           11.17
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      59
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     127
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               2
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      47
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               2
```

**Comment by jrbenito** [comment]
@shred,

What driver is binding the receiver? logitech_dj or hid_generic? I bet it is hid_generic... Anyway, without a Dell receiver I can´t try but if you would like, I think you can start cloning this repository into your Linux and modifying

1. `lib/logitech_receiver/base_usb.py`, add your receiver to the list. Since it is not logitech (vid 046d) you need to create a new lambda at line 33 similar to the line 32 but changing '0x046d' to '0x413c'. And, using this new lambda, do something similar to line 40. Finally, add the device to ALL at the end.

Something similar to:

```
# each tuple contains (vendor_id, product_id, usb interface number, hid driver)
_unifying_receiver = lambda product_id: (0x046d, product_id, 2, _UNIFYING_DRIVER)
_nano_receiver = lambda product_id: (0x046d, product_id, 1, _GENERIC_DRIVER)
_nano_dell_receiver = lambda product_id: (0x413c, product_id, 1, _GENERIC_DRIVER)
[...]
# Nano receviers that support the Unifying protocol
NANO_RECEIVER_ADVANCED    = _nano_receiver(0xc52f)
NANO_DELL_ADVANCED = _nano_dell_receiver(0x301c)
[...]
ALL = (
		UNIFYING_RECEIVER_C52B,
		UNIFYING_RECEIVER_C532,
		NANO_RECEIVER_ADVANCED,
                NANO_DELL_ADVANCED,
[...]
```

Note that I am assuming that Dell receiver is bind by generic_hid driver, if it uses logitech DJ driver, modify accordingly. 

2. You will also need to modify the udev rule that set permissions to logitech devices to do the same with your dell device. Check it in `Solaar/rules.d/42-logitech-unify-permissions.rules` for an example but this you need to modify in your system, not the repository source code.

After that, cross your fingers and, in the repository directory run `bin/solaar show`. If it recognizes your device submit a PR, be happy and get me a beer. But I would expect some other adjustments would have to be made. Try it and if it is really compatible with logitech you can investigate further.

Regards,
JrBenito

**Comment by jrbenito** [comment]
@Lekensteyn 

No answer for a long time. No access to similar device. No way to confirm the claim.

Let´s close this one.

**Comment by shred** [comment]
I'm sorry for not answering.

Yes, it's detected as a hid_generic, not a Logitech one.

Actually I'm not having much time for trying to add the receiver myself, as I'm busy with my own projects, so I close this bug. If I'm successful with adding the receiver as you described in your comment above, I will send a pull request. Thank you for explaining the steps I would have to do.

**Comment by gitdode** [comment]
Just in case anyone is interested - I've tried this and I got:

`18:16:56,573  WARNING [MainThread] logitech_receiver.base: timeout (1.80/1.80) on device 255 request {83B5} params [03]
18:16:56,573    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path=u'/dev/hidraw2', vendor_id=u'413c', product_id=u'8505', serial=u'', release='1119', manufacturer='Dell', product='Dell Universal Receiver', interface=1, driver=u'hid-generic')
Traceback (most recent call last):
  File "/home/user/Linux/Solaar/lib/logitech_receiver/receiver.py", line 529, in open
    return Receiver(handle, device_info)
  File "/home/user/Linux/Solaar/lib/logitech_receiver/receiver.py", line 341, in __init__
    assert serial_reply
AssertionError
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
solaar: error: Logitech receiver not found
`

Since there was a timeout I suppose the receiver didn't even respond? Is it worth digging into this a bit further or is the device so different that it doesn't make sense?
