### ISSUE TITLE
Wireless Link not encrypted

### ISSUE THREAD

**Issue by rikmendes** [pwr/Solaar#320]
I was wondering if this behavior is dependent on the receiver ?
if so I guess "nano receiver" don't support wireless link encryption, correct ?

if that is the case is there any model that actually encrypt this signal ?
![screenshot from 2016-12-02 20-00-55](https://cloud.githubusercontent.com/assets/12155003/20846472/16c0bc4c-b8ca-11e6-91ea-ea77ca03e673.png)

**Comment by Lekensteyn** [comment]
The information is applicable to the protocol used by Unifying receivers. I have no idea if it is also valid for Nano receivers. So, it is possible that the link is actually encrypted, but not reported as such. Or maybe not, you would have to check the specifications for that.

**Comment by parkerlreed** [comment]
I think encryption is only for some keyboards (To protect typing data being sniffed) I do not believe any mice offer the encrypted link.

**Comment by jrbenito** [comment]
As far as I know, link encryption is only available for some devices and I only saw it being applied to Keyboards so far. 

@Lekensteyn ,

My nano receiver paired to MK270 (M185 + K270 non unifying) encrypts the keyboard but not mice. My K270 unifying is encrypted while my M510 and Anywhere MX are not encrypted, both unifying.

**Comment by SlySven** [comment]
As I commented on a different issue, keyboard encryption is pretty much a requirement to avoid rouge third parties sniffing keypresses for things like passwords!

However, unless you are using an on-screen keyboard AND a malevolent eavesdropper knows exactly where everything is on your display then knowing mouse movements is not likely to reveal any sensitive data - which is why mice are not normally capable of encryption.  

Nevertheless, for mice that can be programmed to send keystrokes the lack of encryption may become significant - but only if they are configured to put out sensitive data or more realistically __if they can be hacked to inject normal keystrokes into your system from a remote, hostile agent__...

**Comment by jrbenito** [comment]
@Lekensteyn ,

I think this can be closed.

**Comment by MestreLion** [comment]
For those concerned about wireless link encryption, it's a good idea to update the Unifying Receiver firmware, as pre-2019 models (and perhaps later ones too) had a vulnerability that allowed sniffing:
https://support.logi.com/hc/en-us/community/posts/360033207154-Logitech-Unifying-Receiver-Update
