### ISSUE TITLE
k780 switch fx key

### ISSUE THREAD

**Issue by JulesdeCube** [pwr/Solaar#507]
hello and, thanks for all your work 
I have a k780 all work correctly but who can I use by default the fn key(f1, f2, f3,...) and not the media key.

**Comment by nclm** [comment]
Hi,
I just got of a K780 as well, and installed Solaar uniquely to change the behaviour of the FX keys back to normal. I can't however see the option in the UI but [this doc](/pwr/Solaar/blob/master/docs/devices.md) said that FN swap is meant to be supported on this model. How does it work?

**Comment by nclm** [comment]
Here is how the window looks like:

![Screenshot from 2019-03-16 17-07-44](https://user-images.githubusercontent.com/923008/54478025-1de80e00-480e-11e9-8992-4deb3ec23d1a.png)

The command line version return this:

```
solaar-cli config 2
solaar-cli: error: no settings for K780 Multi-Device Wireless Keyboard
```

I'm using Solaar 0.9.2 from the default Ubuntu repo. Could that be the issue?

**Comment by nclm** [comment]
Alright, it was indeed a version issue. I removed the package and installed manually the version on Github in the master branch.

Nothing changed in the interface and it still mistakenly presents itself as version 0.9.2.

But the option was now available in the command line version:

```
solaar config 2
Wireless Solar Keyboard K780 (K780) [405B:E8413BD5]

# Swap Fx function
# When set, the F1..F12 keys will activate their special function, and you must hold the FN key to activate their standard function.  When unset, the F1..F12 keys will activate their standard function, and you must hold the FN key to activate their special function.
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
fn-swap = True
```

```
solaar config 2 fn-swap "false"
# Swap Fx function
fn-swap = False
```

It works! Mission accomplished. Thanks for the work on this piece of software.

A few suggestions:
* Change the version number of the master branch so that it is clear that it is not the same version than the previous release
* Make some online version of the documentation of the command line, it took me a while to figure out I had to type `solaar config 2 fn-swap "false"`.
* Add this feature in the GUI version.
* The K780 is not solar, so `Wireless Solar Keyboard K780` is a little mistake :)

**Comment by nclm** [comment]
I restarted my computer and the option is in the window now!

![Screenshot from 2019-03-16 17-51-16](https://user-images.githubusercontent.com/923008/54478598-33f8cd00-4814-11e9-91f8-1f54962a7a19.png)

(sorry for the flood of successive comments!)

**Comment by souperk** [comment]
I also own a k780, after setting fn-swap off i can properly use the fx keys. However, insert key is still mapped.

I use the latest version of master branch on github.
