### ISSUE TITLE
Install Master Branch Version on Debian?

### ISSUE THREAD

**Issue by CCamastro** [pwr/Solaar#528]
I am trying to make the fn-swap available for my K400+ on Debian. All the threads on this I've seen, so far, have mentioned something about installing the "master branch version" but I haven't found any detailed information on how to actually do this. 

Would anyone mind taking a few minutes to lay out the steps for using the master branch version? Please assume that I am a git/deb novice and that I couldn't make sense of the [manual installation doc](https://github.com/pwr/Solaar/blob/master/docs/installation.md).

Please and thank you.

**Comment by callmebob2016** [comment]
Download the code for the master branch (if you click [here](https://github.com/pwr/Solaar) and then the green 'Clone or Download' button. Save it on the HDD and unpack it. Then you need to replace existing files in your system with the files that you just downloaded. So for example in your current /usr/bin you probably have the old solaar and solaar-cli files. These need to be replaced with the new once from your newly downloaded /bin directory. Same goes for the new files in /lib, /rules.d, /share.

Also just to be on a safe side, don't just overwrite the existing files. Move them to an ./old directory so you can always revert changes in a clean way. 

Also you need to have the requirements meet like python/gir1.2 packages etc, but since you are updating I reckon that should already be sorted. Just in case you want to make sure you have the packages you can do: 

`sudo dpkg -l | grep package_name`

This will show you if you have the package and what version. 

Hope this helps!

**Comment by CCamastro** [comment]
This did the trick. Thank you!

I first opened the root file directory
`sudo pcmanfm`

Then copied rules.d/42-logitech-unify-permissions.rules to /etc/udev/rules.d; and copied the files in the /bin, /lib, and /share folders to their respective folders of the same name under /usr.

This worked for me after a reboot. I was able to switch off the fn keys from the GUI.
